-- ============================================================================
--  V1 · Núcleo de identidad y clasificación
--  Gastonomo · EIF509 · Laboratorio 2
--
--  Qué crea esta migración:
--    · Los tipos enumerados del vocabulario cerrado que usan estas tablas.
--    · El disparador común que mantiene actualizado_en.
--    · usuario            → raíz de aislamiento de todo el sistema.
--    · cuenta_correo      → buzones vinculados de los que se leen comprobantes.
--    · categoria_estandar → taxonomía global que siembra cada cuenta nueva.
--    · categoria          → clasificación jerárquica propia de cada titular.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  Tipos enumerados
--
--  Un ENUM de PostgreSQL, y no un VARCHAR con CHECK, porque estos son conjuntos
--  que el negocio NO permite inventar sobre la marcha. El tipo se declara una
--  vez y todas las columnas que lo usan quedan validadas por igual; con CHECK
--  habría que repetir (y mantener sincronizada) la misma lista en cada tabla.
-- ----------------------------------------------------------------------------
CREATE TYPE moneda AS ENUM ('CRC', 'USD', 'EUR');

CREATE TYPE proveedor_correo AS ENUM ('GMAIL', 'OUTLOOK');

CREATE TYPE estado_cuenta_correo AS ENUM ('ACTIVA', 'TOKEN_EXPIRADO', 'DESVINCULADA');


-- ----------------------------------------------------------------------------
--  Disparador común de auditoría
--
--  creado_en se resuelve con DEFAULT now(), pero actualizado_en tiene que
--  refrescarse en cada UPDATE. Dejarlo en manos de la aplicación significaría
--  que un UPDATE hecho desde psql o desde un script de mantenimiento dejaría la
--  marca vieja. El disparador lo garantiza venga de donde venga la escritura.
-- ----------------------------------------------------------------------------
CREATE FUNCTION set_actualizado_en() RETURNS TRIGGER AS $$
BEGIN
    NEW.actualizado_en := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ----------------------------------------------------------------------------
--  usuario
--
--  Raíz de aislamiento: toda consulta del sistema se filtra por usuario_id, de
--  modo que cualquier persona pueda registrarse sin ver los datos de nadie más.
-- ----------------------------------------------------------------------------
CREATE TABLE usuario (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo  VARCHAR(120) NOT NULL,
    correo           VARCHAR(180) NOT NULL,
    contrasena_hash  VARCHAR(255) NOT NULL,
    moneda_preferida moneda       NOT NULL DEFAULT 'CRC',
    activo           BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_en   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- El correo identifica la cuenta: es la llave natural con la que se inicia
    -- sesión, así que no puede repetirse.
    CONSTRAINT uq_usuario_correo UNIQUE (correo),

    -- Validación de forma, no de existencia. Atrapa el dato basura antes de que
    -- entre; que el buzón exista de verdad lo confirma el correo de activación.
    CONSTRAINT ck_usuario_correo_formato
        CHECK (correo ~ '^[^@[:space:]]+@[^@[:space:]]+\.[A-Za-z]{2,}$'),

    CONSTRAINT ck_usuario_nombre_no_vacio
        CHECK (btrim(nombre_completo) <> ''),

    -- Nunca se guarda la contraseña, solo su hash. La longitud mínima descarta
    -- que alguien inserte texto plano corto por error.
    CONSTRAINT ck_usuario_hash_longitud
        CHECK (length(contrasena_hash) >= 20),

    -- Habilita las llaves foráneas compuestas que verifican, en la propia base,
    -- que una fila hija pertenece al mismo titular que su padre. Ver V3 y V4.
    CONSTRAINT uq_usuario_id_correo UNIQUE (id, correo)
);

CREATE TRIGGER tg_usuario_actualizado_en
    BEFORE UPDATE ON usuario
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON TABLE usuario IS
    'Persona dueña de su cuenta y de sus datos. Raíz de aislamiento del sistema.';


-- ----------------------------------------------------------------------------
--  cuenta_correo
--
--  Se separa de usuario porque una persona puede vincular más de un buzón (el
--  personal y el del trabajo), porque los tokens caducan por su cuenta y hay
--  que renovarlos, y porque desvincular un correo no puede implicar borrar la
--  cuenta. Un campo direccion dentro de usuario no soportaría ninguna de las
--  tres cosas.
-- ----------------------------------------------------------------------------
CREATE TABLE cuenta_correo (
    id                     BIGINT               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id             BIGINT               NOT NULL,
    proveedor              proveedor_correo     NOT NULL,
    direccion              VARCHAR(180)         NOT NULL,
    token_acceso_cifrado   TEXT                 NOT NULL,
    token_refresco_cifrado TEXT                 NOT NULL,
    expira_en              TIMESTAMPTZ          NOT NULL,
    ultima_sincronizacion  TIMESTAMPTZ,
    estado                 estado_cuenta_correo NOT NULL DEFAULT 'ACTIVA',
    creado_en              TIMESTAMPTZ          NOT NULL DEFAULT now(),
    actualizado_en         TIMESTAMPTZ          NOT NULL DEFAULT now(),

    -- RESTRICT y no CASCADE: dar de baja una cuenta no puede hacer desaparecer
    -- en silencio el rastro de los buzones que tuvo vinculados. La baja del
    -- titular se hace con activo = FALSE, no con DELETE.
    CONSTRAINT fk_cuenta_correo_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    -- El mismo buzón no se vincula dos veces a la misma cuenta. Sí puede estar
    -- en dos cuentas distintas: es el correo de una persona, no del sistema.
    CONSTRAINT uq_cuenta_correo_usuario_direccion UNIQUE (usuario_id, direccion),

    CONSTRAINT ck_cuenta_correo_direccion_formato
        CHECK (direccion ~ '^[^@[:space:]]+@[^@[:space:]]+\.[A-Za-z]{2,}$'),

    -- Ver la nota de uq_usuario_id_correo: sostiene las FK compuestas de V3.
    CONSTRAINT uq_cuenta_correo_id_usuario UNIQUE (id, usuario_id)
);

CREATE INDEX ix_cuenta_correo_usuario ON cuenta_correo (usuario_id);

CREATE TRIGGER tg_cuenta_correo_actualizado_en
    BEFORE UPDATE ON cuenta_correo
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON COLUMN cuenta_correo.token_acceso_cifrado IS
    'Token OAuth cifrado por la aplicación antes de llegar aquí. La base nunca ve el valor en claro.';


-- ----------------------------------------------------------------------------
--  categoria_estandar
--
--  Taxonomía global de ~15 categorías con la que se siembra toda cuenta nueva,
--  para que nadie arranque con una lista vacía.
--
--  Existe además por una razón de integridad: el catálogo de comercios es
--  COMPARTIDO entre todos los titulares (lo administra el rol Administrador),
--  mientras que las categorías son PROPIAS de cada titular. Si comercio
--  apuntara directo a categoria, la sugerencia de un comercio señalaría la
--  categoría de un usuario cualquiera. El comercio sugiere una categoría
--  estándar; cada titular resuelve esa estándar contra la suya propia.
-- ----------------------------------------------------------------------------
CREATE TABLE categoria_estandar (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR(40) NOT NULL,
    nombre         VARCHAR(80) NOT NULL,
    descripcion    VARCHAR(255),
    color_hex      CHAR(7)     NOT NULL DEFAULT '#6B7280',
    orden          SMALLINT    NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- El código, y no el nombre, es la llave estable: el nombre visible puede
    -- reescribirse ('Alimentación' → 'Comida') sin romper las referencias.
    CONSTRAINT uq_categoria_estandar_codigo UNIQUE (codigo),
    CONSTRAINT ck_categoria_estandar_codigo_formato CHECK (codigo ~ '^[A-Z][A-Z0-9_]{2,39}$'),
    CONSTRAINT ck_categoria_estandar_color CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_categoria_estandar_orden CHECK (orden > 0)
);

CREATE TRIGGER tg_categoria_estandar_actualizado_en
    BEFORE UPDATE ON categoria_estandar
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();


-- ----------------------------------------------------------------------------
--  categoria
--
--  Clasificación jerárquica del gasto: Alimentación → Supermercado. La
--  jerarquía se autorreferencia con categoria_padre_id. Solo las categorías
--  hoja reciben gasto directo; las padre existen para totalizar.
-- ----------------------------------------------------------------------------
CREATE TABLE categoria (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id            BIGINT      NOT NULL,
    categoria_padre_id    BIGINT,
    categoria_estandar_id BIGINT,
    nombre                VARCHAR(80) NOT NULL,
    descripcion           VARCHAR(255),
    color_hex             CHAR(7)     NOT NULL DEFAULT '#6B7280',
    es_hoja               BOOLEAN     NOT NULL DEFAULT TRUE,
    activa                BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_categoria_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    CONSTRAINT fk_categoria_padre
        FOREIGN KEY (categoria_padre_id) REFERENCES categoria (id) ON DELETE RESTRICT,

    -- De qué categoría de la taxonomía global nació esta. Es lo que permite
    -- que la sugerencia de un comercio compartido aterrice en la categoría
    -- propia del titular. NULL cuando el titular la creó él mismo.
    CONSTRAINT fk_categoria_estandar
        FOREIGN KEY (categoria_estandar_id) REFERENCES categoria_estandar (id) ON DELETE RESTRICT,

    CONSTRAINT uq_categoria_usuario_nombre UNIQUE (usuario_id, nombre),

    -- Una categoría no puede colgar de sí misma. No cubre ciclos más largos
    -- (A→B→A): eso no lo expresa un CHECK de fila y lo valida el servicio.
    CONSTRAINT ck_categoria_padre_distinta
        CHECK (categoria_padre_id IS NULL OR categoria_padre_id <> id),

    CONSTRAINT ck_categoria_color CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_categoria_nombre_no_vacio CHECK (btrim(nombre) <> ''),

    -- Cada titular deriva a lo sumo una categoría propia de cada estándar; si
    -- no, resolver 'el comercio sugiere ALIMENTACION' sería ambiguo.
    CONSTRAINT uq_categoria_usuario_estandar UNIQUE (usuario_id, categoria_estandar_id),

    -- Sostiene la FK compuesta de linea_compra, presupuesto y
    -- regla_categorizacion: garantiza en la base que una categoría referenciada
    -- pertenece al mismo titular que la fila que la referencia.
    CONSTRAINT uq_categoria_id_usuario UNIQUE (id, usuario_id)
);

CREATE INDEX ix_categoria_padre ON categoria (categoria_padre_id);

CREATE TRIGGER tg_categoria_actualizado_en
    BEFORE UPDATE ON categoria
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON COLUMN categoria.es_hoja IS
    'Redundante con la existencia de hijas: se persiste porque la pantalla de captura la consulta en cada renglón. Lo mantiene el servicio al crear una hija.';
