-- ============================================================================
--  V2 · Catálogos de apoyo
--  Gastonomo · EIF509 · Laboratorio 2
--
--  Qué crea esta migración:
--    · comercio     → catálogo COMPARTIDO de establecimientos (lo administra
--                     el rol Administrador; no pertenece a ningún titular).
--    · metodo_pago  → medios de pago PROPIOS de cada titular.
--    · tipo_cambio  → histórico de tasas por fecha.
--
--  Las tres tablas alimentan a compra, que se crea en V3. Van antes porque una
--  llave foránea no puede apuntar a una tabla que todavía no existe.
-- ============================================================================


CREATE TYPE tipo_metodo_pago AS ENUM (
    'EFECTIVO', 'DEBITO', 'CREDITO', 'SINPE_MOVIL', 'TRANSFERENCIA'
);


-- ----------------------------------------------------------------------------
--  comercio
--
--  El nombre que llega en los comprobantes es sucio ('AUTOMERCADO #12 SAN
--  PEDRO'), así que se guarda además una forma normalizada con la que se
--  agrupan las variantes. Esa forma normalizada es la llave de resolución de
--  la ingesta, y por eso es única en todo el sistema.
--
--  No lleva usuario_id: el catálogo es compartido. Si cada titular tuviera el
--  suyo, se repetiría la misma normalización de 'AUTOMERCADO' en cada cuenta y
--  la corrección de una variante mal escrita no beneficiaría a nadie más.
-- ----------------------------------------------------------------------------
CREATE TABLE comercio (
    id                             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_estandar_sugerida_id BIGINT,
    nombre                         VARCHAR(160) NOT NULL,
    nombre_normalizado             VARCHAR(160) NOT NULL,
    identificacion_tributaria      VARCHAR(20),
    provincia                      VARCHAR(40),
    creado_en                      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_en                 TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- El comercio sugiere una categoría de la taxonomía GLOBAL, no la categoría
    -- de un titular concreto: ver la nota de categoria_estandar en V1.
    -- NULL cuando la ingesta creó el comercio y nadie lo ha clasificado aún.
    CONSTRAINT fk_comercio_categoria_estandar
        FOREIGN KEY (categoria_estandar_sugerida_id)
        REFERENCES categoria_estandar (id) ON DELETE RESTRICT,

    -- Llave de agrupación de la ingesta: dos filas con el mismo nombre
    -- normalizado serían el mismo negocio duplicado, y la resolución del
    -- comercio dejaría de ser determinista.
    CONSTRAINT uq_comercio_nombre_normalizado UNIQUE (nombre_normalizado),

    -- La cédula jurídica de Costa Rica es de 10 dígitos; la física, 9. Se
    -- guarda solo dígitos, sin guiones, para que la comparación sea directa.
    CONSTRAINT ck_comercio_identificacion
        CHECK (identificacion_tributaria IS NULL
               OR identificacion_tributaria ~ '^[0-9]{9,12}$'),

    -- La normalización es mayúsculas sin espacios sobrantes. Se verifica aquí
    -- para que una carga manual no pueda meter una forma sin normalizar.
    CONSTRAINT ck_comercio_nombre_normalizado_forma
        CHECK (nombre_normalizado = btrim(upper(nombre_normalizado))
               AND nombre_normalizado <> '')
);

CREATE TRIGGER tg_comercio_actualizado_en
    BEFORE UPDATE ON comercio
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON TABLE comercio IS
    'Catálogo compartido de establecimientos. La categoría sugerida es la pieza central de la clasificación automática: el comprobante solo trae el nombre del negocio.';


-- ----------------------------------------------------------------------------
--  metodo_pago
--
--  Los últimos cuatro dígitos no son un dato cosmético: son la llave con la que
--  el sistema decide a cuál tarjeta del titular corresponde un cargo que llegó
--  por correo. Solo se guardan esos cuatro, nunca el número completo.
-- ----------------------------------------------------------------------------
CREATE TABLE metodo_pago (
    id             BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT           NOT NULL,
    alias          VARCHAR(60)      NOT NULL,
    tipo           tipo_metodo_pago NOT NULL,
    moneda         moneda           NOT NULL DEFAULT 'CRC',
    ultimos_cuatro CHAR(4),
    entidad        VARCHAR(80),
    dia_corte      SMALLINT,
    activo         BOOLEAN          NOT NULL DEFAULT TRUE,
    creado_en      TIMESTAMPTZ      NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ      NOT NULL DEFAULT now(),

    CONSTRAINT fk_metodo_pago_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    CONSTRAINT uq_metodo_pago_usuario_alias UNIQUE (usuario_id, alias),

    CONSTRAINT ck_metodo_pago_ultimos_cuatro
        CHECK (ultimos_cuatro IS NULL OR ultimos_cuatro ~ '^[0-9]{4}$'),

    -- Solo las tarjetas tienen últimos cuatro dígitos. El efectivo con un
    -- '0000' inventado ensuciaría el emparejamiento de la ingesta.
    CONSTRAINT ck_metodo_pago_ultimos_cuatro_solo_tarjeta
        CHECK (tipo IN ('DEBITO', 'CREDITO') OR ultimos_cuatro IS NULL),

    -- El día de corte solo tiene sentido en una tarjeta de crédito.
    CONSTRAINT ck_metodo_pago_dia_corte
        CHECK ((tipo = 'CREDITO' AND (dia_corte IS NULL OR dia_corte BETWEEN 1 AND 31))
               OR (tipo <> 'CREDITO' AND dia_corte IS NULL)),

    CONSTRAINT uq_metodo_pago_id_usuario UNIQUE (id, usuario_id)
);

CREATE INDEX ix_metodo_pago_usuario ON metodo_pago (usuario_id);

-- Emparejamiento de la ingesta: dado el titular y los cuatro dígitos que trajo
-- el correo, encontrar su tarjeta. Es UNIQUE y no un índice común a propósito:
-- si el titular tuviera dos tarjetas terminadas en 6411, el emparejamiento
-- sería ambiguo y la ingesta cargaría el gasto a la tarjeta equivocada. El
-- modelo prefiere impedirlo a resolverlo adivinando.
CREATE UNIQUE INDEX uq_metodo_pago_usuario_ultimos_cuatro
    ON metodo_pago (usuario_id, ultimos_cuatro)
    WHERE ultimos_cuatro IS NOT NULL;

CREATE TRIGGER tg_metodo_pago_actualizado_en
    BEFORE UPDATE ON metodo_pago
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();


-- ----------------------------------------------------------------------------
--  tipo_cambio
--
--  Histórico de tasas POR FECHA: una compra hecha en dólares el 3 de marzo se
--  convierte siempre con la tasa del 3 de marzo.
--
--  No tiene llave foránea desde compra a propósito: la compra guarda copiada la
--  tasa que se le aplicó, no una referencia. Si apuntara a esta fila, corregir
--  una tasa mal cargada cambiaría retroactivamente los totales de compras ya
--  cerradas.
-- ----------------------------------------------------------------------------
CREATE TABLE tipo_cambio (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moneda_origen   moneda         NOT NULL,
    moneda_destino  moneda         NOT NULL,
    fecha           DATE           NOT NULL,
    tasa            NUMERIC(14, 6) NOT NULL,
    fuente          VARCHAR(60)    NOT NULL DEFAULT 'BCCR',
    creado_en       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- Una sola tasa por par de monedas y fecha. Con dos, la conversión de una
    -- compra dependería de cuál fila leyera la consulta.
    CONSTRAINT uq_tipo_cambio_par_fecha UNIQUE (moneda_origen, moneda_destino, fecha),

    CONSTRAINT ck_tipo_cambio_tasa_positiva CHECK (tasa > 0),
    CONSTRAINT ck_tipo_cambio_monedas_distintas CHECK (moneda_origen <> moneda_destino)
);

-- Consulta real de la conversión: 'la tasa USD→CRC más reciente que no pase de
-- la fecha de esta compra'. El orden descendente por fecha deja la fila buscada
-- en el primer lugar del recorrido del índice.
CREATE INDEX ix_tipo_cambio_busqueda
    ON tipo_cambio (moneda_origen, moneda_destino, fecha DESC);

CREATE TRIGGER tg_tipo_cambio_actualizado_en
    BEFORE UPDATE ON tipo_cambio
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
