-- ============================================================================
--  V3 · Núcleo transaccional
--  Gastonomo · EIF509 · Laboratorio 2
--
--  Qué crea esta migración:
--    · compra       → encabezado del gasto, con sus totales congelados.
--    · linea_compra → renglón de la compra, con su propia categoría.
--    · comprobante  → constancia del correo del que nació una compra.
--
--  Es la parte del sistema que exige consistencia inmediata: los totales tienen
--  que cuadrar, la conciliación escribe en varias tablas a la vez y ninguna
--  escritura puede quedar a medias. Por eso vive completa en PostgreSQL.
-- ============================================================================


CREATE TYPE estado_compra AS ENUM ('BORRADOR', 'REGISTRADA', 'CONCILIADA', 'ANULADA');

CREATE TYPE origen_compra AS ENUM ('MANUAL', 'INGESTA_CORREO', 'FACTURA_XML');

CREATE TYPE estado_comprobante AS ENUM (
    'RECIBIDO', 'PARSEADO', 'PROCESADO', 'REVISION_MANUAL', 'FALLIDO'
);


-- ----------------------------------------------------------------------------
--  compra
--
--  Los totales se persisten calculados en vez de derivarse en cada consulta:
--  un gasto histórico debe seguir mostrando lo que se pagó aunque después
--  cambie el IVA o se corrija la tasa del día. Ver la sección de normalización
--  en docs/modelo-de-datos.md.
-- ----------------------------------------------------------------------------
CREATE TABLE compra (
    id                    BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id            BIGINT         NOT NULL,
    comercio_id           BIGINT         NOT NULL,
    metodo_pago_id        BIGINT,
    fecha                 DATE           NOT NULL,
    descripcion           VARCHAR(255),
    moneda                moneda         NOT NULL DEFAULT 'CRC',
    estado                estado_compra  NOT NULL DEFAULT 'BORRADOR',
    origen                origen_compra  NOT NULL DEFAULT 'MANUAL',
    subtotal              NUMERIC(14, 2) NOT NULL DEFAULT 0,
    descuento             NUMERIC(14, 2) NOT NULL DEFAULT 0,
    impuesto              NUMERIC(14, 2) NOT NULL DEFAULT 0,
    impuesto_desglosado   BOOLEAN        NOT NULL DEFAULT FALSE,
    total                 NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tipo_cambio_aplicado  NUMERIC(14, 6) NOT NULL DEFAULT 1,
    total_moneda_base     NUMERIC(14, 2) NOT NULL DEFAULT 0,
    requiere_revision     BOOLEAN        NOT NULL DEFAULT FALSE,
    creado_en             TIMESTAMPTZ    NOT NULL DEFAULT now(),
    actualizado_en        TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT fk_compra_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    CONSTRAINT fk_compra_comercio
        FOREIGN KEY (comercio_id) REFERENCES comercio (id) ON DELETE RESTRICT,

    -- Compuesta: el método de pago tiene que ser del MISMO titular que la
    -- compra. Una FK simple hacia metodo_pago(id) aceptaría el id de la tarjeta
    -- de otra persona; esta no. Es la validación de aislamiento entre cuentas,
    -- expresada en el esquema en lugar de confiarla al servicio.
    CONSTRAINT fk_compra_metodo_pago
        FOREIGN KEY (metodo_pago_id, usuario_id)
        REFERENCES metodo_pago (id, usuario_id) ON DELETE RESTRICT,

    CONSTRAINT ck_compra_montos_no_negativos
        CHECK (subtotal >= 0 AND descuento >= 0 AND impuesto >= 0 AND total >= 0),

    -- El descuento global no se prorratea entre renglones: se resta después de
    -- sumar. Este CHECK es la fórmula del dominio escrita en la base.
    CONSTRAINT ck_compra_total_cuadra
        CHECK (total = subtotal - descuento + impuesto),

    -- Ningún descuento puede superar el monto sobre el que se aplica.
    CONSTRAINT ck_compra_descuento_acotado CHECK (descuento <= subtotal),

    CONSTRAINT ck_compra_tipo_cambio_positivo CHECK (tipo_cambio_aplicado > 0),

    -- Una compra en la moneda base no lleva conversión: su tasa es exactamente
    -- 1. Sin esta regla, un 1.0001 mal cargado descuadraría el reporte.
    CONSTRAINT ck_compra_moneda_base_sin_conversion
        CHECK (moneda <> 'CRC' OR tipo_cambio_aplicado = 1),

    -- La conversión también se verifica en la base, no solo en el servicio.
    CONSTRAINT ck_compra_total_base_cuadra
        CHECK (total_moneda_base = round(total * tipo_cambio_aplicado, 2)),

    -- Una compra que entró por correo nunca trae el desglose del impuesto: el
    -- total ya viene con IVA incluido y no se sabe qué parte era exenta.
    CONSTRAINT ck_compra_ingesta_sin_desglose
        CHECK (origen <> 'INGESTA_CORREO' OR impuesto_desglosado = FALSE),

    CONSTRAINT uq_compra_id_usuario UNIQUE (id, usuario_id)
);

CREATE TRIGGER tg_compra_actualizado_en
    BEFORE UPDATE ON compra
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON COLUMN compra.fecha IS
    'La regla "no puede ser futura" no se expresa como CHECK: PostgreSQL exige que las funciones de un CHECK sean IMMUTABLE y CURRENT_DATE es STABLE. La valida el servicio.';


-- ----------------------------------------------------------------------------
--  linea_compra
--
--  Renglón de una compra, con su propia categoría. Una compra ingerida por
--  correo nace con un único renglón por el monto total; el desglose es un
--  refinamiento manual posterior.
-- ----------------------------------------------------------------------------
CREATE TABLE linea_compra (
    id                          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id                   BIGINT         NOT NULL,

    -- Redundante con compra.usuario_id: existe únicamente para poder exigir con
    -- llaves foráneas compuestas que la compra y la categoría del renglón sean
    -- del mismo titular. Es la única desnormalización de la V3 y se documenta
    -- en docs/modelo-de-datos.md.
    usuario_id                  BIGINT         NOT NULL,

    categoria_id                BIGINT,
    descripcion                 VARCHAR(255)   NOT NULL,
    cantidad                    NUMERIC(12, 3) NOT NULL DEFAULT 1,
    precio_unitario             NUMERIC(14, 2) NOT NULL,
    descuento                   NUMERIC(14, 2) NOT NULL DEFAULT 0,
    exento_impuesto             BOOLEAN        NOT NULL DEFAULT FALSE,
    subtotal                    NUMERIC(14, 2) NOT NULL,
    categorizada_automaticamente BOOLEAN       NOT NULL DEFAULT FALSE,
    creado_en                   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    actualizado_en              TIMESTAMPTZ    NOT NULL DEFAULT now(),

    -- CASCADE, al contrario que en el resto del esquema: un renglón no tiene
    -- ninguna existencia fuera de su compra. Es la única relación de composición
    -- real del modelo.
    CONSTRAINT fk_linea_compra_compra
        FOREIGN KEY (compra_id, usuario_id)
        REFERENCES compra (id, usuario_id) ON DELETE CASCADE,

    -- Compuesta con usuario_id: solo se puede clasificar en una categoría del
    -- propio titular. NULL únicamente mientras la compra está en BORRADOR.
    CONSTRAINT fk_linea_compra_categoria
        FOREIGN KEY (categoria_id, usuario_id)
        REFERENCES categoria (id, usuario_id) ON DELETE RESTRICT,

    CONSTRAINT ck_linea_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT ck_linea_precio_no_negativo CHECK (precio_unitario >= 0),
    CONSTRAINT ck_linea_descuento_no_negativo CHECK (descuento >= 0),
    CONSTRAINT ck_linea_descuento_acotado CHECK (descuento <= cantidad * precio_unitario),
    CONSTRAINT ck_linea_descripcion_no_vacia CHECK (btrim(descripcion) <> ''),

    -- La fórmula del renglón, verificada por la base:
    -- cantidad × precio_unitario − descuento.
    CONSTRAINT ck_linea_subtotal_cuadra
        CHECK (subtotal = round(cantidad * precio_unitario - descuento, 2))
);

-- Recorrer los renglones de una compra es la consulta más frecuente del
-- sistema: la hace cada vez que se abre el detalle de un gasto.
CREATE INDEX ix_linea_compra_compra ON linea_compra (compra_id);

CREATE TRIGGER tg_linea_compra_actualizado_en
    BEFORE UPDATE ON linea_compra
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON CONSTRAINT ck_linea_subtotal_cuadra ON linea_compra IS
    'Todo monto se maneja con NUMERIC y redondeo a dos decimales: con punto flotante 0.1 + 0.2 no da 0.3 y un reporte de gastos que no cuadra por céntimos no sirve.';


-- ----------------------------------------------------------------------------
--  comprobante
--
--  NO guarda el correo. El sistema lee el mensaje, extrae los cuatro campos que
--  necesita y descarta el contenido. Lo que queda aquí es la constancia de que
--  ese mensaje ya se procesó —lo que hace idempotente la ingesta— y la
--  trazabilidad de qué correo originó cada compra.
-- ----------------------------------------------------------------------------
CREATE TABLE comprobante (
    id                     BIGINT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id             BIGINT             NOT NULL,
    cuenta_correo_id       BIGINT             NOT NULL,
    compra_id              BIGINT,
    mensaje_id             VARCHAR(255)       NOT NULL,
    remitente              VARCHAR(180)       NOT NULL,
    recibido_en            TIMESTAMPTZ        NOT NULL,
    estado                 estado_comprobante NOT NULL DEFAULT 'RECIBIDO',
    confianza_parseo       NUMERIC(4, 3),
    intentos_procesamiento SMALLINT           NOT NULL DEFAULT 0,
    motivo_fallo           TEXT,
    creado_en              TIMESTAMPTZ        NOT NULL DEFAULT now(),
    actualizado_en         TIMESTAMPTZ        NOT NULL DEFAULT now(),

    CONSTRAINT fk_comprobante_cuenta_correo
        FOREIGN KEY (cuenta_correo_id, usuario_id)
        REFERENCES cuenta_correo (id, usuario_id) ON DELETE RESTRICT,

    CONSTRAINT fk_comprobante_compra
        FOREIGN KEY (compra_id, usuario_id)
        REFERENCES compra (id, usuario_id) ON DELETE RESTRICT,

    -- El corazón de la idempotencia de la ingesta: si el buzón reentrega el
    -- mismo mensaje, el INSERT falla en vez de duplicar el gasto. Es por buzón
    -- y no global porque el identificador de mensaje solo es único dentro del
    -- proveedor que lo emitió.
    CONSTRAINT uq_comprobante_buzon_mensaje UNIQUE (cuenta_correo_id, mensaje_id),

    CONSTRAINT ck_comprobante_confianza
        CHECK (confianza_parseo IS NULL OR confianza_parseo BETWEEN 0 AND 1),

    -- Un comprobante que falla tres veces pasa a FALLIDO y se le notifica al
    -- titular: no hay un cuarto intento.
    CONSTRAINT ck_comprobante_intentos CHECK (intentos_procesamiento BETWEEN 0 AND 3),

    -- Un fallo sin motivo no es diagnosticable.
    CONSTRAINT ck_comprobante_fallo_con_motivo
        CHECK (estado <> 'FALLIDO' OR btrim(coalesce(motivo_fallo, '')) <> ''),

    -- Un comprobante PROCESADO es, por definición, el que ya originó su compra.
    CONSTRAINT ck_comprobante_procesado_con_compra
        CHECK (estado <> 'PROCESADO' OR compra_id IS NOT NULL)
);

-- Una compra nace de un comprobante como máximo: dos comprobantes apuntando a
-- la misma compra significarían que el mismo gasto se contó dos veces.
CREATE UNIQUE INDEX uq_comprobante_compra
    ON comprobante (compra_id)
    WHERE compra_id IS NOT NULL;

CREATE TRIGGER tg_comprobante_actualizado_en
    BEFORE UPDATE ON comprobante
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
