-- ============================================================================
--  V4 · Presupuestos y reglas de categorización
--  Gastonomo · EIF509 · Laboratorio 2
--
--  Qué crea esta migración:
--    · presupuesto           → tope de gasto de una categoría para un mes.
--    · regla_categorizacion  → lo que el sistema aprende de las correcciones.
--
--  Van después del núcleo transaccional porque ambas son consecuencia suya: el
--  presupuesto se consume cuando se registra una compra, y la regla nace cuando
--  el titular corrige la categoría de un renglón.
-- ============================================================================


CREATE TYPE estado_presupuesto AS ENUM ('ACTIVO', 'CERRADO');

-- Sobre qué texto se evalúa el patrón de una regla. Cerrado a propósito: si
-- fuera texto libre, una regla podría apuntar a un campo inexistente y el motor
-- de categorización fallaría en tiempo de ejecución en vez de al guardarla.
CREATE TYPE campo_regla AS ENUM (
    'COMERCIO_NORMALIZADO', 'DESCRIPCION_COMPRA', 'DESCRIPCION_LINEA'
);


-- ----------------------------------------------------------------------------
--  presupuesto
--
--  monto_consumido se acumula en la fila en vez de sumarse en cada consulta
--  porque el frontend lo muestra en vivo: recalcular la suma de todas las
--  compras del mes en cada refresco de pantalla no escala.
-- ----------------------------------------------------------------------------
CREATE TABLE presupuesto (
    id              BIGINT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT             NOT NULL,
    categoria_id    BIGINT             NOT NULL,
    anio            SMALLINT           NOT NULL,
    mes             SMALLINT           NOT NULL,
    monto_limite    NUMERIC(14, 2)     NOT NULL,
    monto_consumido NUMERIC(14, 2)     NOT NULL DEFAULT 0,
    moneda          moneda             NOT NULL DEFAULT 'CRC',
    umbral_alerta   SMALLINT           NOT NULL DEFAULT 80,
    estado          estado_presupuesto NOT NULL DEFAULT 'ACTIVO',
    creado_en       TIMESTAMPTZ        NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMPTZ        NOT NULL DEFAULT now(),

    CONSTRAINT fk_presupuesto_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    -- Compuesta: solo se presupuesta una categoría propia. Ver la nota de
    -- fk_compra_metodo_pago en V3.
    CONSTRAINT fk_presupuesto_categoria
        FOREIGN KEY (categoria_id, usuario_id)
        REFERENCES categoria (id, usuario_id) ON DELETE RESTRICT,

    -- Un solo presupuesto por categoría y mes. Con dos, el avance mostrado en
    -- pantalla dependería de cuál fila leyera la consulta.
    CONSTRAINT uq_presupuesto_usuario_categoria_periodo
        UNIQUE (usuario_id, categoria_id, anio, mes),

    CONSTRAINT ck_presupuesto_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_presupuesto_anio CHECK (anio BETWEEN 2000 AND 2100),

    -- Un tope de cero no es un presupuesto, es una categoría prohibida: eso se
    -- modela desactivando la categoría, no poniendo el límite en cero.
    CONSTRAINT ck_presupuesto_limite_positivo CHECK (monto_limite > 0),

    -- Puede superar el límite (justamente para eso existe la alerta), pero
    -- nunca ser negativo: anular una compra devuelve su monto, no lo resta dos
    -- veces.
    CONSTRAINT ck_presupuesto_consumido_no_negativo CHECK (monto_consumido >= 0),

    CONSTRAINT ck_presupuesto_umbral CHECK (umbral_alerta BETWEEN 1 AND 100)
);

-- Consulta de la pantalla de inicio: 'los presupuestos de este titular para
-- este mes'. Es la que se ejecuta en cada carga y en cada actualización en vivo.
CREATE INDEX ix_presupuesto_usuario_periodo ON presupuesto (usuario_id, anio, mes);

CREATE TRIGGER tg_presupuesto_actualizado_en
    BEFORE UPDATE ON presupuesto
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

COMMENT ON COLUMN presupuesto.monto_consumido IS
    'Acumulado, no derivado en cada consulta. Se mantiene dentro de la misma transacción que registra la compra, que es lo que impide que se desincronice.';


-- ----------------------------------------------------------------------------
--  regla_categorizacion
--
--  Nace de que el titular corrija una categoría, no de que entre a una pantalla
--  de configuración. Es lo que hace que el sistema mejore con el uso sin
--  pedirle a nadie que configure reglas a mano.
-- ----------------------------------------------------------------------------
CREATE TABLE regla_categorizacion (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id           BIGINT      NOT NULL,
    categoria_destino_id BIGINT      NOT NULL,
    nombre               VARCHAR(80) NOT NULL,
    campo                campo_regla NOT NULL DEFAULT 'COMERCIO_NORMALIZADO',
    patron               VARCHAR(200) NOT NULL,
    prioridad            SMALLINT    NOT NULL,
    activa               BOOLEAN     NOT NULL DEFAULT TRUE,
    veces_aplicada       INTEGER     NOT NULL DEFAULT 0,
    creado_en            TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_regla_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE RESTRICT,

    CONSTRAINT fk_regla_categoria_destino
        FOREIGN KEY (categoria_destino_id, usuario_id)
        REFERENCES categoria (id, usuario_id) ON DELETE RESTRICT,

    CONSTRAINT uq_regla_usuario_nombre UNIQUE (usuario_id, nombre),

    -- Las reglas se evalúan por prioridad ascendente y gana la primera que
    -- coincide. Si dos reglas del mismo titular compartieran prioridad, el
    -- resultado de la categorización dependería del orden en que la base
    -- devolviera las filas: la misma compra podría caer en una categoría
    -- distinta cada vez. La unicidad de la prioridad es lo que hace
    -- determinista el motor de reglas.
    CONSTRAINT uq_regla_usuario_prioridad UNIQUE (usuario_id, prioridad),

    CONSTRAINT ck_regla_prioridad_positiva CHECK (prioridad > 0),
    CONSTRAINT ck_regla_patron_no_vacio CHECK (btrim(patron) <> ''),
    CONSTRAINT ck_regla_veces_no_negativas CHECK (veces_aplicada >= 0)
);

-- Recorrido del motor de reglas: 'las reglas activas de este titular, en orden
-- de prioridad'. El índice parcial deja fuera las desactivadas, que nunca se
-- evalúan, y el orden de la prioridad evita ordenar en memoria.
CREATE INDEX ix_regla_evaluacion
    ON regla_categorizacion (usuario_id, prioridad)
    WHERE activa;

CREATE TRIGGER tg_regla_actualizado_en
    BEFORE UPDATE ON regla_categorizacion
    FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
