-- ============================================================================
--  V6 · Lo que la capa de negocio le exige al esquema
--  Gastonomo · EIF509 · Laboratorio 4
--
--  El Laboratorio 2 modeló el dominio tal como lo describía la propuesta. Al
--  implementar los servicios (Laboratorio 4) aparecieron dos diferencias
--  reales entre ese modelo y lo que el negocio necesita. Esta migración las
--  corrige, porque la regla del curso es que el esquema cambia únicamente con
--  migraciones nuevas -nunca con lo que la aplicación cree al arrancar.
--
--  Qué cambia:
--    · comercio_categoria_sugerida → tabla nueva. La categoría sugerida deja
--      de ser un campo de `comercio` y pasa a ser por (titular, comercio).
--    · comprobante                 → las columnas del parseo que la ingesta
--      guarda, y el tipo de cambio con el que se selló cada uno.
--
--  Lo que NO cambia: ninguna columna existente cambia de tipo ni se borra. La
--  única que se toca se renombra (`confianza_parseo` → `confianza`), que
--  conserva los datos. Una migración que se aplica sobre una base con datos no
--  puede permitirse perder ninguno.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  1 · comercio_categoria_sugerida
--
--  La propuesta de dominio modela la categoría sugerida como un campo directo
--  de `comercio` (`categoria_sugerida_id`). Al construir la clasificación
--  automática quedó claro que ese modelo rompe el aislamiento entre cuentas:
--  `comercio` es un catálogo COMPARTIDO por todos los titulares y `categoria`
--  es exclusiva de cada uno. Una sugerencia global significaría que la
--  categoría "Mascotas" del titular A clasifique las compras del titular B
--  -que ni siquiera tiene por qué tener esa categoría.
--
--  La sugerencia es entonces por el par (usuario, comercio). Es la corrección
--  de un error de modelado, no una entidad nueva del dominio: sigue siendo "la
--  categoría sugerida del comercio", solo que de quién la sugirió.
--
--  Nace de «corregir crea la regla»: cuando un titular cambia la categoría de
--  un cargo, esta fila hace que la próxima compra en el mismo comercio entre
--  ya clasificada.
-- ----------------------------------------------------------------------------
CREATE TABLE comercio_categoria_sugerida (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT NOT NULL,
    comercio_id  BIGINT NOT NULL REFERENCES comercio (id) ON DELETE RESTRICT,
    categoria_id BIGINT NOT NULL,

    -- Llave compuesta, igual que el resto de las tablas hijas del titular: la
    -- base garantiza que la categoría sugerida pertenezca a quien la sugiere,
    -- en vez de dejar esa regla a que la aplicación se acuerde de validarla.
    CONSTRAINT fk_comercio_categoria_categoria
        FOREIGN KEY (categoria_id, usuario_id)
        REFERENCES categoria (id, usuario_id) ON DELETE CASCADE,

    -- Un titular sugiere una sola categoría por comercio. Sin esto, dos filas
    -- para el mismo par harían no determinista la clasificación automática.
    CONSTRAINT uq_comercio_categoria_usuario_comercio UNIQUE (usuario_id, comercio_id)
);

COMMENT ON TABLE comercio_categoria_sugerida IS
    'La categoría que un titular concreto le asignó a un comercio del catálogo compartido. Reemplaza al campo categoria_sugerida_id de comercio, que rompía el aislamiento entre cuentas.';

--  La consulta que lo justifica -la ejecuta la conciliación de CADA
--  comprobante y el registro manual de CADA renglón sin categoría:
--
--      SELECT categoria_id FROM comercio_categoria_sugerida
--       WHERE usuario_id = :u AND comercio_id = :c;
--
--  La restricción UNIQUE de arriba ya crea el índice que la resuelve, así que
--  no se agrega ninguno más: un índice solo por comercio_id no serviría (la
--  consulta siempre filtra por titular primero) y encarecería cada INSERT.


-- ----------------------------------------------------------------------------
--  2 · comprobante · los campos del parseo
--
--  V3 modeló `comprobante` como la constancia de que un mensaje ya se procesó:
--  identificador, remitente, fecha, estado. Correcto para la idempotencia de la
--  ingesta, pero incompleto para lo que el negocio terminó necesitando: sin los
--  campos extraídos, cada pantalla que muestra gasto tendría que volver a leer
--  y reparsear la bandeja del proveedor en cada petición -con una bandeja de
--  cien mensajes, cien peticiones HTTP a Microsoft o Google por cada carga.
--
--  Estas columnas son la caché de ese trabajo. Todas admiten NULL a propósito:
--  un comprobante incompleto es un caso normal del negocio -va a revisión
--  manual- no un error, y las filas que ya existían no tienen estos datos.
--
--  El cuerpo del correo sigue sin almacenarse: se leen estos campos y se
--  descarta. Ver «Subdominio documental candidato» en la propuesta de dominio.
-- ----------------------------------------------------------------------------
ALTER TABLE comprobante
    ADD COLUMN banco            VARCHAR(80),
    ADD COLUMN comercio         VARCHAR(200),
    ADD COLUMN ciudad           VARCHAR(120),
    ADD COLUMN pais             VARCHAR(120),
    ADD COLUMN fecha            TIMESTAMP,
    ADD COLUMN marca_tarjeta    VARCHAR(40),
    ADD COLUMN ultimos_cuatro   VARCHAR(4),
    ADD COLUMN autorizacion     VARCHAR(60),
    ADD COLUMN referencia       VARCHAR(60),
    ADD COLUMN tipo_transaccion VARCHAR(40),
    ADD COLUMN moneda           VARCHAR(3),
    ADD COLUMN monto            NUMERIC(14, 2);

--  `fecha` es TIMESTAMP sin zona, a diferencia de `recibido_en`: es la hora
--  local que el banco escribe en la notificación, no un instante del sistema.
--  Convertirla a TIMESTAMPTZ obligaría a inventarle una zona horaria.
COMMENT ON COLUMN comprobante.fecha IS
    'Fecha y hora de la compra según el texto de la notificación bancaria: hora local, sin zona. Distinta de recibido_en, que es cuándo llegó el mensaje.';

COMMENT ON COLUMN comprobante.ultimos_cuatro IS
    'Los cuatro últimos dígitos de la tarjeta, la llave con la que se empareja el metodo_pago del titular. Nunca se guarda el número completo.';

ALTER TABLE comprobante
    ADD CONSTRAINT ck_comprobante_monto_positivo
        CHECK (monto IS NULL OR monto > 0),
    ADD CONSTRAINT ck_comprobante_ultimos_cuatro
        CHECK (ultimos_cuatro IS NULL OR ultimos_cuatro ~ '^[0-9]{4}$');

--  V3 llamó `confianza_parseo` a la confianza del parseo; el mapeo la llama
--  `confianza`. Un nombre distinto para el mismo dato obliga a traducirlo en
--  cada consulta, y tarde o temprano alguien lo olvida. Se renombra la columna
--  -no se agrega otra- para no duplicar el dato ni perder el que ya hubiera:
--  PostgreSQL arrastra el rename a los CHECK que la referencian.
ALTER TABLE comprobante RENAME COLUMN confianza_parseo TO confianza;


-- ----------------------------------------------------------------------------
--  3 · comprobante · el tipo de cambio con el que se selló
--
--  El Banco Central publica tipos de cambio históricos solo con suscripción, y
--  el respaldo (Hacienda) únicamente el del día. Sin guardar nada, convertir
--  una compra de hace tres meses obliga a usar la tasa de hoy, que no es la
--  que se pagó.
--
--  `tipo_cambio_fecha` es de qué día es la tasa, y no siempre coincide con
--  `fecha`: al sincronizar por primera vez una bandeja vieja se guarda la tasa
--  de hoy para compras de hace meses. Sin esta columna no habría forma de
--  distinguir una tasa contemporánea de una tardía, y el total parecería más
--  preciso de lo que es.
-- ----------------------------------------------------------------------------
ALTER TABLE comprobante
    ADD COLUMN tipo_cambio_venta NUMERIC(12, 4),
    ADD COLUMN tipo_cambio_fecha DATE;

ALTER TABLE comprobante
    ADD CONSTRAINT ck_comprobante_tipo_cambio_positivo
        CHECK (tipo_cambio_venta IS NULL OR tipo_cambio_venta > 0),
    -- Una tasa sin la fecha a la que corresponde no es un dato: es una cifra
    -- suelta que no se puede auditar.
    ADD CONSTRAINT ck_comprobante_tipo_cambio_con_fecha
        CHECK ((tipo_cambio_venta IS NULL) = (tipo_cambio_fecha IS NULL));
