-- ============================================================================
--  V7 · Identidad con Google y transferencias SINPE
--  Gastonomo · EIF509 · Laboratorio 4
--
--  Las funcionalidades que el equipo adelantó fuera del orden de los
--  laboratorios también cambiaron el esquema, y hasta ahora esos cambios solo
--  existían porque la aplicación corría `Base.metadata.create_all()` al
--  arrancar. Esta migración los trae a Flyway, para que sea la única fuente de
--  verdad del esquema.
--
--  Va aparte de V6 a propósito: V6 es lo que exige la capa de negocio que se
--  evalúa en el Laboratorio 4; esto es lo que exigen funcionalidades que están
--  fuera de esa entrega. Separarlas permite entender cada migración por lo que
--  responde, y aplicar solo V1–V6 en un despliegue que no necesite ninguna de
--  las dos cosas.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  1 · usuario · iniciar sesión con Google
--
--  Una cuenta puede nacer de dos formas: con correo y contraseña, o con
--  Google. Por eso `contrasena_hash` deja de ser obligatoria -una cuenta que
--  llegó solo por Google no tiene ninguna que guardar- y aparece `google_id`.
--
--  El CHECK de abajo es lo que impide el caso que ninguna de las dos columnas
--  por separado puede evitar: una cuenta sin contraseña Y sin Google, es
--  decir, una cuenta en la que nadie puede entrar nunca.
-- ----------------------------------------------------------------------------
ALTER TABLE usuario
    ALTER COLUMN contrasena_hash DROP NOT NULL;

ALTER TABLE usuario
    ADD COLUMN google_id VARCHAR(255);

--  El identificador que da Google (`sub`) es único por cuenta de Google. La
--  unicidad acá impide que dos titulares de este sistema queden ligados a la
--  misma cuenta de Google. Es UNIQUE y no PRIMARY KEY porque la mayoría de las
--  filas lo tienen en NULL, y en PostgreSQL varios NULL no chocan entre sí.
ALTER TABLE usuario
    ADD CONSTRAINT uq_usuario_google UNIQUE (google_id);

ALTER TABLE usuario
    ADD CONSTRAINT ck_usuario_tiene_como_entrar
        CHECK (contrasena_hash IS NOT NULL OR google_id IS NOT NULL);

COMMENT ON COLUMN usuario.google_id IS
    'El "sub" de Google, si el titular vinculó su cuenta. NULL en las cuentas que solo usan correo y contraseña.';


-- ----------------------------------------------------------------------------
--  2 · usuario · leer transferencias SINPE
--
--  Apagado por defecto, y esa no es una preferencia estética: sincronizar
--  transferencias es una petición real más por cada buzón vinculado, cada vez.
--  Encenderlo es una decisión del titular, no el comportamiento por omisión.
-- ----------------------------------------------------------------------------
ALTER TABLE usuario
    ADD COLUMN leer_transferencias_sinpe BOOLEAN NOT NULL DEFAULT FALSE;


-- ----------------------------------------------------------------------------
--  3 · transferencia_sinpe
--
--  Una notificación de SINPE recibida, ya leída. No es una `Compra`: una
--  transferencia que entra es dinero que llega, no gasto -por eso vive en su
--  propia tabla y no alimenta presupuestos ni reportes de gasto.
--
--  `confirmado` distingue lo que leyó un lector validado contra una
--  notificación real de ese banco (BAC, Banco Nacional) de lo que leyó el
--  lector genérico, que busca patrones sueltos en vez de una plantilla fija.
--  El genérico es menos preciso, así que nunca se hace pasar por uno exacto:
--  la pantalla muestra sus resultados marcados para revisar.
-- ----------------------------------------------------------------------------
--  A diferencia del resto de las tablas hijas del titular, esta no propaga
--  `usuario_id`: se consulta siempre por buzón (`listar_de_cuenta`,
--  `mensajes_ya_sincronizados`) y nunca por titular, así que la columna sería
--  una que nadie lee. El aislamiento entre cuentas lo garantiza igual la
--  cadena `transferencia_sinpe → cuenta_correo → usuario`, un salto más largo
--  pero con la misma restricción de la base detrás.
CREATE TABLE transferencia_sinpe (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_correo_id BIGINT       NOT NULL REFERENCES cuenta_correo (id) ON DELETE CASCADE,
    mensaje_id       VARCHAR(300) NOT NULL,
    banco            VARCHAR(80)  NOT NULL,
    destinatario     VARCHAR(200),
    cuenta_destino   VARCHAR(40),
    fecha            TIMESTAMP,
    moneda           VARCHAR(3),
    monto            NUMERIC(14, 2),
    concepto         VARCHAR(300),
    referencia       VARCHAR(60),
    comprobante      VARCHAR(60),
    confianza        NUMERIC(4, 3) NOT NULL,
    confirmado       BOOLEAN       NOT NULL DEFAULT FALSE,

    -- La misma idempotencia que `comprobante`: si el buzón reentrega el mismo
    -- mensaje, el INSERT falla en vez de duplicar la transferencia.
    CONSTRAINT uq_transferencia_buzon_mensaje UNIQUE (cuenta_correo_id, mensaje_id),

    CONSTRAINT ck_transferencia_confianza CHECK (confianza BETWEEN 0 AND 1),
    CONSTRAINT ck_transferencia_monto_positivo CHECK (monto IS NULL OR monto > 0)
);

COMMENT ON TABLE transferencia_sinpe IS
    'Transferencias SINPE recibidas, leídas del buzón. Dinero que entra, no gasto: no alimenta presupuestos ni reportes de gasto.';

COMMENT ON COLUMN transferencia_sinpe.confirmado IS
    'TRUE solo si la leyó un lector validado contra una notificación real de ese banco. FALSE si la leyó el lector genérico: la pantalla la muestra marcada para revisar.';

--  La consulta que lo justifica -`TransferenciaSinpeRepository.listar_de_cuenta`,
--  la que alimenta la pantalla SINPE:
--
--      SELECT ... FROM transferencia_sinpe
--       WHERE cuenta_correo_id = :c ORDER BY fecha DESC;
--
--  El UNIQUE de (cuenta_correo_id, mensaje_id) no la resuelve: su segunda
--  columna es el identificador del mensaje, no la fecha, así que serviría para
--  filtrar pero no para evitar el ordenamiento.
CREATE INDEX ix_transferencia_sinpe_buzon_fecha
    ON transferencia_sinpe (cuenta_correo_id, fecha DESC);
